### ISSUE TITLE
Make configurable the poseidon parameters

### ISSUE THREAD

**Issue by drewstone** [webb-tools/poseidon#1]
I would generalise the `new()` function over potential changes to the parameters. This would allow downstream apps more flexibility. We can default to the parameters that are currently set there.

**Comment by shekohex** [comment]
I will expose a builder pattern for the hasher, the same as we do in Rust!

**Comment by shekohex** [comment]
Closed in 6ef94fe9b082067d3b67991f880f413beeb0fda9
